### ISSUE TITLE
Does not respond due to UnicodeDecodeError

### ISSUE THREAD

**Issue by Gresley** [MrJohnZoidberg/Snips-Wetter#2]
raspberrypi snips-skill-server[376]: INFO:snips_skill_server_lib::runner: [searchWeatherForecast-Wetter][err] return cls(session_id.encode('utf-8'), text.encode('utf-8')) 
raspberrypi snips-skill-server[376]: INFO:snips_skill_server_lib::runner: [searchWeatherForecast-Wetter][err] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 76:

**Comment by guywhocodes** [comment]
Das Problem besteht leider immer noch:

```
Nov 26 22:03:56 raspberrypi snips-skill-server[21829]: INFO:snips_skill_server_lib::runner: [searchWeatherForecast-Wetter][err] Traceback (most recent call last):
Nov 26 22:03:56 raspberrypi snips-skill-server[21829]: INFO:snips_skill_server_lib::runner: [searchWeatherForecast-Wetter][err]   File "_ctypes/callbacks.c", line 315, in 'calling callback function'
Nov 26 22:03:56 raspberrypi snips-skill-server[21829]: INFO:snips_skill_server_lib::runner: [searchWeatherForecast-Wetter][err]   File "/var/lib/snips/skills/Snips-Wetter/venv/local/lib/python2.7/site-packages/hermes_python/hermes.py", line 55, in called_with_good_params
Nov 26 22:03:56 raspberrypi snips-skill-server[21829]: INFO:snips_skill_server_lib::runner: [searchWeatherForecast-Wetter][err]     return func(self, *parsed_args)
Nov 26 22:03:56 raspberrypi snips-skill-server[21829]: INFO:snips_skill_server_lib::runner: [searchWeatherForecast-Wetter][err]   File "./action-searchWeatherForecast-Wetter.py", line 30, in subscribe_intent_callback
Nov 26 22:03:56 raspberrypi snips-skill-server[21829]: INFO:snips_skill_server_lib::runner: [searchWeatherForecast-Wetter][err]     hermes.publish_end_session(intentMessage.session_id, weather.forecast(intentMessage))
Nov 26 22:03:56 raspberrypi snips-skill-server[21829]: INFO:snips_skill_server_lib::runner: [searchWeatherForecast-Wetter][err]   File "/var/lib/snips/skills/Snips-Wetter/venv/local/lib/python2.7/site-packages/hermes_python/hermes.py", line 170, in publish_end_session
Nov 26 22:03:56 raspberrypi snips-skill-server[21829]: INFO:snips_skill_server_lib::runner: [searchWeatherForecast-Wetter][err]     cEndSessionMessage = CEndSessionMessage.build(session_id, text)
Nov 26 22:03:56 raspberrypi snips-skill-server[21829]: INFO:snips_skill_server_lib::runner: [searchWeatherForecast-Wetter][err]   File "/var/lib/snips/skills/Snips-Wetter/venv/local/lib/python2.7/site-packages/hermes_python/ffi/ontology.py", line 64, in build
Nov 26 22:03:56 raspberrypi snips-skill-server[21829]: INFO:snips_skill_server_lib::runner: [searchWeatherForecast-Wetter][err]     b_text = text.encode('utf-8') if text else None
Nov 26 22:03:56 raspberrypi snips-skill-server[21829]: INFO:snips_skill_server_lib::runner: [searchWeatherForecast-Wetter][err] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 76: ordinal not in range(128)
```

**Comment by amjadsaadeh** [comment]
Hallo,
in `/var/lib/snips/skills/Snips-Wetter/wather.py` in Line 111 ist ein "ö", welches ich in ein "oe" geändert habe. Nach dem Neustart des Skill-Servers lief es soweit problemlos. Außer das man das "oe" deutlich hören kann :(

**Comment by amjadsaadeh** [comment]
Ich hab mir das nochmal genau angesehen und man muss scheinbar alle Strings mit Umlauten mit einem "u" prefixen, damit daraus ein unicode string wird.

**Comment by dominiczedler** [comment]
Jetzt sollten alle Unicode Fehler weg sein, weil ich die App nach Python 3 portiert habe.
